version: "3.9"

services:
  auto-data-analyst:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app/reports:/app/app/reports
      - ./app/tmp:/app/app/tmp
    restart: unless-stopped
